version: "3"

tasks:
  install:
    deps:
      - build
    cmds:
      - cp dist/deploy_dagger{{OS}}_{{ARCH}}_v1/deploy-dagger $GOBIN
    silent: true
  build:
    cmds:
      - goreleaser build --snapshot --single-target --rm-dist
    silent: true
  release:
    cmds:
      - goreleaser release --rm-dist
    silent: true