name: goreleaser-deploy-dagger

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: v1.4.1
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Docker build and push
        run: |
          docker build -t jaronnie/deploy-dagger:${{ steps.get_version.outputs.VERSION }} .
          docker push jaronnie/deploy-dagger:${{ steps.get_version.outputs.VERSION }}
          docker tag jaronnie/deploy-dagger:${{ steps.get_version.outputs.VERSION }} jaronnie/deploy-dagger:latest
          docker push jaronnie/deploy-dagger:latest

          docker build -t jaronnie/deploy-dagger:${{ steps.get_version.outputs.VERSION }}-arm64 -f Dockerfile-arm64 .
          docker push jaronnie/deploy-dagger:${{ steps.get_version.outputs.VERSION }}-arm64
          docker tag jaronnie/deploy-dagger:${{ steps.get_version.outputs.VERSION }}-arm64 jaronnie/deploy-dagger:latest-arm64
          docker push jaronnie/deploy-dagger:latest-arm64